# Generated by Django 5.0.6 on 2024-06-21 20:47

from django.db import migrations


def add_initial_llm_models(apps, schema_editor):
    LLMModel = apps.get_model('chat', 'LLMModel')
    initial_models = [
        'gpt-4o',
        'gpt-4-turbo',
        'gpt-4',
        'gpt-3.5-turbo',
    ]
    for model_name in initial_models:
        LLMModel.objects.create(name=model_name)


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_initial_llm_models),
    ]
