# Generated by Django 5.0.6 on 2024-06-26 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chat_llm_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='title',
            field=models.CharField(default='New Chat', max_length=200),
        ),
    ]
