# Generated by Django 5.0.6 on 2024-07-12 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_preferred_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='openai_api_quota',
            field=models.IntegerField(default=1000000),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='openai_api_usage',
            field=models.IntegerField(default=0),
        ),
    ]
